---
- hosts: localhost
  connection: local
  vars_files:
    - ~/.python-int-overflow-check/external_vars.yml
  tasks:
    - name: Launch instance
      local_action: ec2
                    aws_access_key={{ aws_access_key }}
                    aws_secret_key={{ aws_secret_key }}
                    keypair={{ aws_keypair }}
                    region={{ aws_region }}
                    image={{ aws_image }}
                    instance_type={{ aws_instance_type }}
                    group={{ aws_security_groups }}
                    count=1
                    wait=yes
      register: ec2

    - name: Add new instance to host group
      local_action: add_host hostname={{ item.public_ip }} groupname=launched
      with_items: ec2.instances

    - name: Wait for SSH to come up
      local_action: wait_for host={{ item.public_dns_name }} port=22 delay=60 timeout=320 state=started
      with_items: ec2.instances

- hosts: launched
  sudo: True
  roles:
    - package_builder

#- hosts: localhost
#  connection: local
#  tasks:
#    - name: Copy source files
#      local_action:
#        shell: cd $WORKSPACE &&
#               rsync -vaz ./ root@{{ item.public_dns_name }}:~/python-intoverflow-check/
#      with_items: ec2.instances

#    - name: Terminate instances that were previously launched
#      local_action:
#        module: ec2
#        state: 'absent'
#        instance_ids: ${ec2.instance_ids}
